import type { SessionContent } from "../types";

export const week4Session2: SessionContent = {
  id: "w4-s2",
  week: 4,
  session: 2,
  concept: "pattern",
  misconception: "описал три элемента — описал закономерность",
  titleRu: "Правило вместо списка",
  explanationRu: "Список из трёх элементов обрывается на десятом. Правило-генератор продолжает само.",
  dinnerQuestionRu: "Попроси описать узор (числа, цвета или звуки) как ПРАВИЛО, а не как список «что было нарисовано».",
  practiceRequired: 3,
  minTier: 1,
  tasks: [
    {
      id: "w4s2-collision",
      role: "collision",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Не перечисляй — скажи правило, которое даст 10 членов.",
      hintRu: "Опиши не ЧТО нарисовано, а КАК это получается.",
      patternExpected: ["1","2","3","4","5","6","7","8","9","10"],
      patternExpandCount: 10,
    },
    {
      id: "w4s2-p1",
      role: "practice",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Старт 1, шаг 1 — до 10-го члена.",
      hintRu: "Генератор, не список.",
      patternExpected: ["1","2","3","4","5","6","7","8","9","10"],
      patternExpandCount: 10,
    },
    {
      id: "w4s2-p2",
      role: "practice",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Старт 0, шаг 3 — десять членов.",
      hintRu: "Как получается следующий?",
      patternExpected: ["0","3","6","9","12","15","18","21","24","27"],
      patternExpandCount: 10,
    },
    {
      id: "w4s2-p3",
      role: "practice",
      family: "pattern-expand",
      tier: 2,
      promptRu: "Цикл: а, б, в — разверни на 10 членов.",
      hintRu: "Правило повтора, не три слова списком.",
      patternExpected: ["а","б","в","а","б","в","а","б","в","а"],
      patternExpandCount: 10,
    },
    {
      id: "w4s2-transfer",
      role: "transfer",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Расскажи, как получена дорожка: старт 5, шаг −1, десять членов.",
      hintRu: "Опиши КАК получается, не что видно.",
      patternExpected: ["5","4","3","2","1","0","-1","-2","-3","-4"],
      patternExpandCount: 10,
    }
  ],
};
