import type { SessionContent } from "../types";

export const week4Session1: SessionContent = {
  id: "w4-s1",
  week: 4,
  session: 1,
  concept: "pattern",
  misconception: "описал три элемента — описал закономерность",
  titleRu: "Что дальше?",
  explanationRu: "Монстр не угадывает продолжение «1, 2, 3 → банан». Ему нужно правило, из которого получаются следующие члены.",
  dinnerQuestionRu: "Попроси описать узор (числа, цвета или звуки) как ПРАВИЛО, а не как список «что было нарисовано».",
  practiceRequired: 3,
  minTier: 1,
  tasks: [
    {
      id: "w4s1-collision",
      role: "collision",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Скажи правило, которое продолжит ряд на 5 следующих членов.",
      hintRu: "Как из одного элемента получается следующий?",
      patternExpected: ["1","2","3","4","5"],
      patternExpandCount: 5,
    },
    {
      id: "w4s1-p1",
      role: "practice",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Начинай с 1 и каждый раз прибавляй 1 — скажи это как правило.",
      hintRu: "Назови старт и шаг.",
      patternExpected: ["1","2","3","4","5"],
      patternExpandCount: 5,
    },
    {
      id: "w4s1-p2",
      role: "practice",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Правило: старт 2, шаг 2. Пять членов.",
      hintRu: "Как получается следующий из предыдущего?",
      patternExpected: ["2","4","6","8","10"],
      patternExpandCount: 5,
    },
    {
      id: "w4s1-p3",
      role: "practice",
      family: "pattern-expand",
      tier: 2,
      promptRu: "Цвета: повторяй красный, синий. Пять членов.",
      hintRu: "Опиши цикл, не список примеров.",
      patternExpected: ["красный","синий","красный","синий","красный"],
      patternExpandCount: 5,
    },
    {
      id: "w4s1-transfer",
      role: "transfer",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Звуки-цвета: цикл жёлтый–зелёный на 5 членов.",
      hintRu: "Как из одного получается следующий?",
      patternExpected: ["жёлтый","зелёный","жёлтый","зелёный","жёлтый"],
      patternExpandCount: 5,
    }
  ],
};
