import type { SessionContent } from "../types";

export const week4Session3: SessionContent = {
  id: "w4-s3",
  week: 4,
  session: 3,
  concept: "pattern",
  misconception: "описал три элемента — описал закономерность",
  titleRu: "Сломанный узор",
  explanationRu: "Одна плитка выбилась. Нужно найти разрыв и починить правило минимальной правкой — не переписывать всё заново.",
  dinnerQuestionRu: "Попроси описать узор (числа, цвета или звуки) как ПРАВИЛО, а не как список «что было нарисовано».",
  practiceRequired: 3,
  minTier: 1,
  tasks: [
    {
      id: "w4s3-collision",
      role: "collision",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Узор сломан. Скажи исправленное правило для всей ленты.",
      hintRu: "Где именно узор перестал слушаться правила?",
      patternExpected: ["1","2","3","4","5","6"],
      patternExpandCount: 6,
    },
    {
      id: "w4s3-p1",
      role: "practice",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Почини: должно быть +1 от 1. Шесть членов.",
      hintRu: "Минимальная правка правила, не новый список.",
      patternExpected: ["1","2","3","4","5","6"],
      patternExpandCount: 6,
    },
    {
      id: "w4s3-p2",
      role: "practice",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Цикл красный–синий–жёлтый на 6 членов — без сбоя.",
      hintRu: "Где узор ломался? Почини правило.",
      patternExpected: ["красный","синий","жёлтый","красный","синий","жёлтый"],
      patternExpandCount: 6,
    },
    {
      id: "w4s3-p3",
      role: "practice",
      family: "pattern-expand",
      tier: 2,
      promptRu: "Старт 10, шаг −2, шесть членов.",
      hintRu: "Самая маленькая правка, чтобы все члены совпали.",
      patternExpected: ["10","8","6","4","2","0"],
      patternExpandCount: 6,
    },
    {
      id: "w4s3-transfer",
      role: "transfer",
      family: "pattern-expand",
      tier: 1,
      promptRu: "Перенос: «почини» последовательность шагов как правило старт 1 шаг 1 на 6 членов.",
      hintRu: "Где узор перестал слушаться?",
      patternExpected: ["1","2","3","4","5","6"],
      patternExpandCount: 6,
    }
  ],
};
